WITH MAX_SIZE_OF_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR)
SELECT M.YEAR, (M.MAX_COLONY - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E, MAX_SIZE_OF_COLONY AS M
WHERE M.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY M.YEAR, YEAR_DEV