WITH USER AS (
    SELECT U.USER_ID, U.NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS     전화번호, COUNT(*) AS USER_COUNT
    FROM USED_GOODS_USER U LEFT JOIN USED_GOODS_BOARD B
        ON U.USER_ID = B.WRITER_ID
    GROUP BY U.USER_ID)
SELECT USER_ID, NICKNAME, 전체주소, 전화번호
FROM USER
WHERE USER_COUNT >= 3
ORDER BY USER_ID DESC